### ISSUE TITLE
what about this " var " code is "let "???

### ISSUE THREAD

**Issue by tsingson** [Paqmind/react-starter#27]
i clone this repo with "git clone " , when i open gulp file.js , there is

<pre>
// DEFAULTS ========================================================================================
let exitOnError = false;
process.env.NODE_CONFIG_DIR = process.env.NODE_CONFIG_DIR || "./shared/config";

// IMPORTS =========================================================================================
let ChildProcess = require("child_process");
let Config = require("config");
let Gulp = require("gulp");
let gulpUtil = require("gulp-util");
let runSequence = require("run-sequence");
let jshintStylish = require("jshint-stylish");
let gulpJshint = require("gulp-jshint");
let gulpCached = require("gulp-cached");
let gulpSourcemaps = require("gulp-sourcemaps");
let gulpLess = require("gulp-less");
let gulpConcat = require("gulp-concat");
let gulpRename = require("gulp-rename");
var gulpUglify = require("gulp-uglify");
let gulp6to5 = require("gulp-6to5");
let gulpPlumber = require("gulp-plumber");
let vinylSource = require("vinyl-source-stream");
let vinylBuffer = require("vinyl-buffer");
</pre>

why ??

and, i find all js  missing "var " but  " let " there .

**Comment by ivan-kleshnin** [comment]
Hi! `let` is a new `var` statement in upcoming ES6. It is better because it's block scoped (see "variable hoisting"). ES6 and ES7 can be translated to ES5 via [Babel](https://babeljs.io/) transpiler.
It's already mainstream.

Translations can be made via gulp tasks and/or at runtime (see `$ babel-node`)

To be able run this gulp file you should run `./bin/fixes/gulp` or copy paste code from there to your terminal (this will replace shebang in `gulp.js` from `node` to `babel-node)

**Comment by tsingson** [comment]
thanks a lot for your kindly reply.
i check for it.
